import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const docsRoot = path.join(root, 'docs')
const newsRoot = path.join(docsRoot, 'news')
const vitepressDir = path.join(docsRoot, '.vitepress')

const MONTH_DIR_RE = /^\d{4}-\d{2}$/

function listMonthDirs() {
  return fs
    .readdirSync(root, { withFileTypes: true })
    .filter((d) => d.isDirectory() && MONTH_DIR_RE.test(d.name))
    .map((d) => d.name)
    .sort()
    .reverse()
}

function copyMonthNews(month) {
  const srcDir = path.join(root, month)
  const destDir = path.join(newsRoot, month)
  fs.mkdirSync(destDir, { recursive: true })

  const files = fs
    .readdirSync(srcDir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .reverse()

  for (const file of files) {
    fs.copyFileSync(path.join(srcDir, file), path.join(destDir, file))
  }

  return files
}

function extractDate(filename) {
  const match = filename.match(/(\d{4}-\d{2}-\d{2})/)
  return match ? match[1] : filename.replace(/\.md$/, '')
}

function buildSidebar(months, monthFiles) {
  return months.map((month) => ({
    text: month,
    collapsed: false,
    items: monthFiles[month].map((file) => {
      const slug = file.replace(/\.md$/, '')
      return {
        text: extractDate(file),
        link: `/news/${month}/${slug}`,
      }
    }),
  }))
}

function buildIndexMarkdown(months, monthFiles) {
  const lines = [
    '---',
    'layout: home',
    'hero:',
    '  name: AI 资讯日报',
    '  text: 每日 AI 模型、产品、论文与行业动态',
    '  tagline: 联网检索 · 来源核验 · 按日归档',
    '  actions:',
    '    - theme: brand',
    '      text: 阅读最新日报',
    '      link: /news/',
    'features:',
    '  - title: 模型与产品',
    '    details: OpenAI、Anthropic、Google 等官方来源优先核验',
    '  - title: 论文与开源',
    '    details: arXiv 研究与 GitHub Trending / HelloGitHub 热门项目',
    '  - title: 行业动态',
    '    details: 政策、融资、安全与 benchmark 趋势',
    '---',
    '',
    '## 最近更新',
    '',
  ]

  const recent = []
  for (const month of months) {
    for (const file of monthFiles[month]) {
      const slug = file.replace(/\.md$/, '')
      recent.push({ month, slug, date: extractDate(file) })
    }
  }

  for (const item of recent.slice(0, 10)) {
    lines.push(`- [${item.date}](/news/${item.month}/${item.slug})`)
  }

  if (recent.length === 0) {
    lines.push('- 暂无日报，请先在仓库根目录生成 `YYYY-MM/ai-news-YYYY-MM-DD.md`')
  }

  lines.push('')
  return lines.join('\n')
}

function writeSidebarModule(sidebar) {
  const content = `// Auto-generated by scripts/sync-news.mjs — do not edit\nexport default ${JSON.stringify(sidebar, null, 2)}\n`
  fs.writeFileSync(path.join(vitepressDir, 'sidebar.generated.mjs'), content, 'utf8')
}

function main() {
  fs.mkdirSync(vitepressDir, { recursive: true })

  if (fs.existsSync(newsRoot)) {
    fs.rmSync(newsRoot, { recursive: true, force: true })
  }

  const months = listMonthDirs()
  const monthFiles = {}

  for (const month of months) {
    monthFiles[month] = copyMonthNews(month)
  }

  const sidebar = buildSidebar(months, monthFiles)
  writeSidebarModule(sidebar)

  fs.writeFileSync(path.join(docsRoot, 'index.md'), buildIndexMarkdown(months, monthFiles), 'utf8')

  const total = months.reduce((n, m) => n + monthFiles[m].length, 0)
  console.log(`Synced ${total} article(s) from ${months.length} month folder(s).`)
}

main()
